name: tasksmanager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+11

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl_utils: ^2.7.0
  #localization
  flutter_localizations:
    sdk: flutter
  #app icon
  flutter_launcher_icons: ^0.11.0
  pull_to_refresh: ^2.0.0
  adaptive_theme: ^3.4.0

  go_router: ^10.1.2
  dartz: ^0.10.1
  get_it: ^7.6.4
  fluttertoast: ^8.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  bloc_concurrency: ^0.2.2
  gradient_borders: ^1.0.0
  http: ^1.2.1
  bloc_test: ^9.1.7
  build_runner_core: ^7.3.1


flutter_icons:
  android: "ic_launcher"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
#    generate: true
#    image_path: "assets/app_icon2.png"
#    background_color: "#021D49"
#    theme_color: "#021D49"
  # then run
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main
  # then you can delete package and photo and these code

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_lints: ^2.0.1
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.11

#  build_runner: ^2.1.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic





flutter_intl:
  enabled: true
